Repository softeerbootcamp-2nd/ios-luckycardgame, pull requests merged in 2023-07, with the labels that each got.

#10 [이수민] 1주차 계획 PR
  README.md
Labels: plan

#9 [양승현] README.md에 이번 주 해야 할 일 추가했습니다.
  README.md
Labels: plan

#11 [오승민] 1주차 학습 계획
  README.md
Labels: plan

#12 [고정민] 1주차 학습 계획
  README.md
Labels: plan

#13 [오승민] 1주차 학습 계획 수정
  README.md
Labels: plan

#20 [정도현] - 게임보드 만들기
  .gitignore
  LuckyCardGame/LuckyCardGame/Application/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/Application/Info.plist
  LuckyCardGame/LuckyCardGame/Application/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets/Assets.xcassets/Contents.json
  LuckyCardGame/LuckyCardGame/Assets/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/View/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/View/PlayerboardView.swift
  LuckyCardGame/LuckyCardGame/View/RoundBoardView.swift
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITestsLaunchTests.swift
  README.md
Labels: step1-1

#21 [변상연] 게임보드 UI 구현
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/sangyeon.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/sangyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets.xcassets/Contents.json
  LuckyCardGame/LuckyCardGame/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/CardBoardViewController.swift
  LuckyCardGame/LuckyCardGame/Info.plist
  LuckyCardGame/LuckyCardGame/PersonalCardBoardView.swift
  LuckyCardGame/LuckyCardGame/RoundView.swift
  LuckyCardGame/LuckyCardGame/SceneDelegate.swift
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITestsLaunchTests.swift
Labels: step1-1

#22 [배남석] 게임 보드 만들기 구현
  .DS_Store
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/baenamseok.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/baenamseok.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame/Info.plist
  LuckyCardGame/LuckyCardGame/View/ContainerView.swift
  LuckyCardGame/LuckyCardGame/ViewController/ViewController.swift
  LuckyCardGame/LuckyCardGame/etc/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/etc/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/LuckyCardGame/etc/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/LuckyCardGame/etc/Assets.xcassets/Contents.json
  LuckyCardGame/LuckyCardGame/etc/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/etc/Info.plist
  LuckyCardGame/LuckyCardGame/etc/SceneDelegate.swift
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITestsLaunchTests.swift
  README.md
Labels: step1-1

#25 [조승기] 게임보드 만들기
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/choseungki.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/choseungki.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame/App/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/App/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/LuckyCardGame/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/LuckyCardGame/App/Assets.xcassets/Contents.json
  LuckyCardGame/LuckyCardGame/App/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/App/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/Info.plist
  LuckyCardGame/LuckyCardGame/View/DeckStackView.swift
  LuckyCardGame/LuckyCardGame/View/DeckView.swift
  LuckyCardGame/LuckyCardGame/View/PaddingLabel.swift
  LuckyCardGame/LuckyCardGame/ViewController/ViewController.swift
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITestsLaunchTests.swift
Labels: step1-1

#28 [양승현] LuckyCardGame proejct 세팅 및 메인 UI 구현
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/yangseunghyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/Source/Common/Model/UIConstant.swift
  LuckyCardGame/Source/Common/Model/UISpacing.swift
  LuckyCardGame/Source/Common/Protocol/ConvenienceInit.swift
  LuckyCardGame/Source/Common/Protocol/LayoutSupport.swift
  LuckyCardGame/Source/Common/View/BaseView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/ContentViewConstant/LuckyCardGameContentView+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/ContentViewConstant/LuckyCardGamePlayerBoardView+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/FooterConstant/LuckyCardGameFooter+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/HeaderConstant/LuckyCardGameHeader+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/LuckyCardGameView+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/PlayerBoardType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/PlayerHeadCountType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Content/LuckyCardGameContentView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Content/PlayerCardBoardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Footer/LuckyCardGameFooter.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Header/LuckyCardGameHeader.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/LuckyCardGameView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewController/LuckyCardGameViewController.swift
  LuckyCardGame/Source/Support/AppDelegate.swift
  LuckyCardGame/Source/Support/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/Source/Support/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/Source/Support/Assets.xcassets/Contents.json
  LuckyCardGame/Source/Support/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/Source/Support/Info.plist
  LuckyCardGame/Source/Support/SceneDelegate.swift
  README.md
Labels: step1-1

#26 [이수민] W1-1 게임보드 만들기 구현
  .DS_Store
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/soom.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/soom.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/soom.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets.xcassets/Contents.json
  LuckyCardGame/LuckyCardGame/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/Base.lproj/Main.storyboard
  LuckyCardGame/LuckyCardGame/Info.plist
  LuckyCardGame/LuckyCardGame/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/ViewController.swift
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITestsLaunchTests.swift
  README.md
Labels: step1-1

#29 [고정민] - 럭키카드 클래스 구현하기
  .DS_Store
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/kojeongmin.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame/Entity/Card.swift
  LuckyCardGame/LuckyCardGame/Entity/CardFactory.swift
  LuckyCardGame/LuckyCardGame/Entity/CardType.swift
  LuckyCardGame/LuckyCardGame/Entity/Deck.swift
  LuckyCardGame/LuckyCardGame/Entity/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/ViewController.swift
Labels: step1-2

#32 [오승민] 게임보드 구현단계 리뷰 반영 및 리펙토링
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/seuoh.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/seuoh.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/View/CardDeckStackView.swift
  LuckyCardGame/LuckyCardGame/View/CardDeckView.swift
Labels: step1-1

#31 [배남석] 럭키카드 클래스 구현하기
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/baenamseok.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame/Model/Class/Card.swift
  LuckyCardGame/LuckyCardGame/Model/Class/CardFactory.swift
  LuckyCardGame/LuckyCardGame/Model/Class/Deck.swift
  LuckyCardGame/LuckyCardGame/Util/Enum/AnimalType.swift
  LuckyCardGame/LuckyCardGame/Util/Enum/CardNumberType.swift
  LuckyCardGame/LuckyCardGame/Util/Extension/UIView+.swift
  LuckyCardGame/LuckyCardGame/View/ContainerView.swift
  LuckyCardGame/LuckyCardGame/ViewController/ViewController.swift
  README.md
Labels: step1-2

#33 [정도현] - 럭키카드 클래스 구현하기, 간편생성자, required init 수정
  LuckyCardGame/LuckyCardGame/Model/CardEmojiType.swift
  LuckyCardGame/LuckyCardGame/Model/CardValue.swift
  LuckyCardGame/LuckyCardGame/Model/CardValueValidator.swift
  LuckyCardGame/LuckyCardGame/Model/Deck.swift
  LuckyCardGame/LuckyCardGame/Model/DeckProtocol.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardMaker.swift
  LuckyCardGame/LuckyCardGame/Model/RandomBuildable.swift
  LuckyCardGame/LuckyCardGame/View/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/View/PlayerboardView.swift
  LuckyCardGame/LuckyCardGame/View/RoundBoardView.swift
Labels: step1-2

#34 [변상연] 럭키카드 클래스 구현
  .DS_Store
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/sangyeon.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/sangyeon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/App/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/App/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/LuckyCardGame/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/LuckyCardGame/App/Assets.xcassets/Contents.json
  LuckyCardGame/LuckyCardGame/App/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/App/Info.plist
  LuckyCardGame/LuckyCardGame/App/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardFactory.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardGame.swift
  LuckyCardGame/LuckyCardGame/View/PersonalCardBoardView.swift
  LuckyCardGame/LuckyCardGame/View/RoundView.swift
  LuckyCardGame/LuckyCardGame/ViewController/CardBoardViewController.swift
  README.md
Labels: step1-2

#37 [안은노] 럭키카드 클래스 구현
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/eunno.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/eunno.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/Model/Animal.swift
  LuckyCardGame/LuckyCardGame/Model/Deck.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/View/PlayerboardView.swift
  LuckyCardGame/LuckyCardGame/View/RoundBoardView.swift
  LuckyCardGame/LuckyCardGame/ViewController.swift
  README.md
Labels: step1-2

#39 [오승민] 럭키카드 클래스 구현
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/seuoh.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/seuoh.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/Model/Card.swift
  LuckyCardGame/LuckyCardGame/Model/CardDeckProtocol.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardDeck.swift
  README.md
Labels: step1-2

#40 [양승현] 럭키카드 클래스 구현
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/Source/Common/String+ToUnicodeTypeString.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Manager/LuckyCardManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/Card.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/CardShapeStorageImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCard.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCardShapeType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Deck/LuckyCardDeckError.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Deck/LuckyCardDeckImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Factory/CardShapeStorageFactoryImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Player/PlayerBoardType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Player/PlayerHeadCountType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardConvertible.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardShapeStorage.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Deck/Deck.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Deck/DeckConvertible.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Factory/CardShapeStorageFactory.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Content/PlayerCardBoardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewController/LuckyCardGameViewController.swift
  README.md
Labels: step1-2

#41 [조승기] 럭키카드 클래스 구현
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame/View/DeckStackView.swift
  LuckyCardGame/LuckyCardGame/ViewController/ViewController.swift
  LuckyCardGame/LuckyCardGame/ViewModel/AnimalType.swift
  LuckyCardGame/LuckyCardGame/ViewModel/Deck.swift
  LuckyCardGame/LuckyCardGame/ViewModel/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/ViewModel/NumberType.swift
  LuckyCardGame/LuckyCardGame/ViewModel/Typeable.swift
Labels: step1-2

#42 [고정민] - (1-1)게임보드 만들기,(1-2) 카드 클래스 리팩토링
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/kojeongmin.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame/Base.lproj/Main.storyboard
  LuckyCardGame/LuckyCardGame/Component/CardContainerView.swift
  LuckyCardGame/LuckyCardGame/Entity/Card.swift
  LuckyCardGame/LuckyCardGame/Entity/CardFactory.swift
  LuckyCardGame/LuckyCardGame/Entity/CardType.swift
  LuckyCardGame/LuckyCardGame/Entity/Deck.swift
  LuckyCardGame/LuckyCardGame/Entity/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Entity/Player.swift
  LuckyCardGame/LuckyCardGame/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/ViewController.swift
  README.md
Labels: step1-1, step1-2

#45 [오승민] 럭키카드 클래스 리뷰 반영 및 리펙토링
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/Model/CardDeckProtocol.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardDeck.swift
  LuckyCardGame/LuckyCardGame/View/CardDeckView.swift
  LuckyCardGame/LuckyCardGame/View/LayoutConstant.swift
  README.md
Labels: step1-2

#47 [배남석] 카드 나눠주기 과제 수행
  .DS_Store
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/baenamseok.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/baenamseok.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/Model/Class/Card.swift
  LuckyCardGame/LuckyCardGame/Model/Class/CardFactory.swift
  LuckyCardGame/LuckyCardGame/Model/Class/Deck.swift
  LuckyCardGame/LuckyCardGame/Model/Class/DefaultLuckyGameManager.swift
  LuckyCardGame/LuckyCardGame/Model/Class/Divider.swift
  LuckyCardGame/LuckyCardGame/Model/Struct/Board.swift
  LuckyCardGame/LuckyCardGame/Util/Enum/BoardNameType.swift
  LuckyCardGame/LuckyCardGame/Util/Enum/DeckCountType.swift
  LuckyCardGame/LuckyCardGame/Util/Enum/PlayerCountType.swift
  LuckyCardGame/LuckyCardGame/Util/Extension/String+.swift
  LuckyCardGame/LuckyCardGame/Util/Extension/UIImage+.swift
  LuckyCardGame/LuckyCardGame/Util/Extension/UILabel+.swift
  LuckyCardGame/LuckyCardGame/View/CardView.swift
  LuckyCardGame/LuckyCardGame/View/ContainerView.swift
  LuckyCardGame/LuckyCardGame/ViewController/ViewController.swift
  LuckyCardGame/LuckyCardGame/etc/Assets.xcassets/CardBackImage.imageset/Contents.json
  LuckyCardGame/LuckyCardGame/etc/Assets.xcassets/CardBackImage.imageset/카드뒷면.png
  README.md
Labels: step1-3

#48 [변상연] 카드 나눠주기 구현
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/xcshareddata/xcschemes/LuckyCardGame.xcscheme
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/byeonsang-yeon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/sangyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame/Info.plist
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardFactory.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardGame.swift
  LuckyCardGame/LuckyCardGame/Resource/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  LuckyCardGame/LuckyCardGame/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  LuckyCardGame/LuckyCardGame/Resource/Assets.xcassets/Contents.json
  LuckyCardGame/LuckyCardGame/Resource/Assets.xcassets/luckycard_back.imageset/Contents.json
  LuckyCardGame/LuckyCardGame/Resource/Assets.xcassets/luckycard_back.imageset/luckycard_back 1.png
  LuckyCardGame/LuckyCardGame/Resource/Assets.xcassets/luckycard_back.imageset/luckycard_back 2.png
  LuckyCardGame/LuckyCardGame/Resource/Assets.xcassets/luckycard_back.imageset/luckycard_back.png
  LuckyCardGame/LuckyCardGame/Resource/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/Resource/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/Source/Class/LuckyCardGame.swift
  LuckyCardGame/LuckyCardGame/Source/Class/LuckyCardManager.swift
  LuckyCardGame/LuckyCardGame/Source/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Source/Model/Player.swift
  LuckyCardGame/LuckyCardGame/Source/View/CardBoardView.swift
  LuckyCardGame/LuckyCardGame/Source/View/LuckyCardView.swift
  LuckyCardGame/LuckyCardGame/Source/View/PersonalCardBoardView.swift
  LuckyCardGame/LuckyCardGame/Source/View/RoundView.swift
  LuckyCardGame/LuckyCardGame/Source/ViewController/CardBoardViewController.swift
  LuckyCardGame/LuckyCardGame/View/PersonalCardBoardView.swift
  LuckyCardGame/LuckyCardGame/ViewController/CardBoardViewController.swift
  README.md
Labels: step1-3

#49 [안은노] 3일차 카드 나눠주기
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/eunno.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/eunno.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/.DS_Store
  LuckyCardGame/LuckyCardGame/Assets.xcassets/cardBackSideImage.imageset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets.xcassets/cardBackSideImage.imageset/cardBackSideImage.png
  LuckyCardGame/LuckyCardGame/Constant/ConstantValue.swift
  LuckyCardGame/LuckyCardGame/Model/AboutCard/Animal.swift
  LuckyCardGame/LuckyCardGame/Model/AboutCard/CardNumber.swift
  LuckyCardGame/LuckyCardGame/Model/AboutCard/Deck.swift
  LuckyCardGame/LuckyCardGame/Model/AboutCard/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/Attendee.swift
  LuckyCardGame/LuckyCardGame/Model/CardDealer.swift
  LuckyCardGame/LuckyCardGame/Model/Deck.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardGame.swift
  LuckyCardGame/LuckyCardGame/Model/Tester.swift
  LuckyCardGame/LuckyCardGame/View/Board/BottomBoardView.swift
  LuckyCardGame/LuckyCardGame/View/Board/PlayerboardView.swift
  LuckyCardGame/LuckyCardGame/View/Board/RoundBoardView.swift
  LuckyCardGame/LuckyCardGame/View/Card/BehindCardView.swift
  LuckyCardGame/LuckyCardGame/View/Card/CardView.swift
  LuckyCardGame/LuckyCardGame/View/Card/FrontCardView.swift
  LuckyCardGame/LuckyCardGame/View/Game/GameView.swift
  LuckyCardGame/LuckyCardGame/View/Game/SegmentedControlView.swift
  LuckyCardGame/LuckyCardGame/View/PlayerboardView.swift
  LuckyCardGame/LuckyCardGame/ViewController.swift
Labels: step1-3

#50 [이수민] W1-3 카드 나눠주기
  .DS_Store
  LuckyCardGame/.DS_Store
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/soom.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/soom.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/AlphabetView.swift
  LuckyCardGame/LuckyCardGame/App/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/App/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/App/ViewController.swift
  LuckyCardGame/LuckyCardGame/Assets.xcassets/clover.imageset/1688135632324square256 (1).png
  LuckyCardGame/LuckyCardGame/Assets.xcassets/clover.imageset/Contents.json
  LuckyCardGame/LuckyCardGame/ConstantSize.swift
  LuckyCardGame/LuckyCardGame/LuckyCard/LuckCardDeck.swift
  LuckyCardGame/LuckyCardGame/LuckyCard/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/LuckyCard/LuckyCardGameManager.swift
  LuckyCardGame/LuckyCardGame/LuckyCard/LuckyCardManager.swift
  LuckyCardGame/LuckyCardGame/LuckyCard/Player.swift
  LuckyCardGame/LuckyCardGame/View/CardView.swift
  LuckyCardGame/LuckyCardGame/View/ConstantSize.swift
  LuckyCardGame/LuckyCardGame/View/ElementView.swift
  LuckyCardGame/LuckyCardGame/ViewController.swift
  README.md
Labels: step1-3

#51 [양승현] Week 1. 2, 3일 PR 코드 리뷰 기반 리펙터링 + 카드 나눠주기
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/Source/Common/Extension/Notification+.swift
  LuckyCardGame/Source/Common/Extension/String+ToUnicodeTypeString.swift
  LuckyCardGame/Source/Common/Extension/UIView+Constant.swift
  LuckyCardGame/Source/Common/Model/BaseViewPalette.swift
  LuckyCardGame/Source/Common/Model/UIConstant.swift
  LuckyCardGame/Source/Common/Protocol/LayoutSupport.swift
  LuckyCardGame/Source/Common/View/BaseRoundView.swift
  LuckyCardGame/Source/Common/View/BaseView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/ContentViewConstant/LuckyCardGameContentView+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/ContentViewConstant/LuckyCardGamePlayerBoardView+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/FooterConstant/LuckyCardGameFooter+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/HeaderConstant/LuckyCardGameHeader+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Constant/LuckyCardGameView+Constant.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Manager/LuckyCardManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/Card.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/CardShapeStorageImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCard.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCardNumbertype.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCardShapeType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Deck/LuckyCardDeckError.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Deck/LuckyCardDeckImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Player/Player.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Player/PlayerBoardType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Player/PlayerHeadCountType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardNumberEnumProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardShapeEnumProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardShapeStorage.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Deck/Deck.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/ViewModel/LuckyCardViewModelProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/ViewModel/PlayersCardBoardAreaViewModelProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Common/CardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Content/LuckyCardGameContentView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Content/PlayerCardBoardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Footer/LuckyCardGameFooter.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Content/LuckyCardGameContentView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Content/PlayerCardBoardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Footer/LuckyCardGameFooter.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/Header/LuckyCardGameHeader.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/LuckyCardGameView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/LuckyCardGameView/LuckyCardGameHeader.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/LuckyCardGameView/LuckyCardGameView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewController/LuckyCardGameViewController.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewController/PlayersCardAreaViewController.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/LuckyCardGameFooterViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/LuckyCardViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/PlayerCardBoardViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/PlayersCardBoardAreaViewModel.swift
  LuckyCardGame/Source/Support/Assets.xcassets/LuckyCard/Contents.json
  LuckyCardGame/Source/Support/Assets.xcassets/LuckyCard/luckyLogo.imageset/Contents.json
  LuckyCardGame/Source/Support/Assets.xcassets/LuckyCard/luckyLogo.imageset/luckyLogo.png
  LuckyCardGame/Source/Support/Assets.xcassets/LuckyCard/luckyLogo.imageset/luckyLogo@2x.png
  LuckyCardGame/Source/Support/Assets.xcassets/LuckyCard/luckyLogo.imageset/luckyLogo@3x.png
  README.md
Labels: step1-3

#58 [양승현] Unit test를 위한 model들 의존성 protocol로 주입하기 위해 리펙터링. 불필요한 model제거. 애니메이션 살짝 도입..
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGameTests/LuckyGame/Manager/LuckyCardGameManagerTests.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Manager/LuckyCardGameManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Manager/LuckyCardManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/Card.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/CardShapeStorageImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCard.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCardNumbertype.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCardShapeType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Deck/LuckyCardDeckImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardGameManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardNumberEnumProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardShapeEnumProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardShapeStorage.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Deck/Deck.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/ViewModel/PlayerCardBoardViewModelProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/ViewModel/PlayersCardBoardAreaViewModelProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Content/LuckyCardGameContentView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Content/PlayerCardBoardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Footer/LuckyCardGameFooter.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewController/PlayersCardAreaViewController.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/LuckyCardGameFooterViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/LuckyCardViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/PlayerCardBoardViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/PlayersCardBoardAreaViewModel.swift
  README.md
Labels: step1-3

#61 [오승민] 카드 분배 UI 구현
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/seuoh.xcuserdatad/xcdebugger/Expressions.xcexplist
  LuckyCardGame/LuckyCardGame.xcodeproj/xcshareddata/xcschemes/LuckyCardGame.xcscheme
  LuckyCardGame/LuckyCardGame/App/AppDelegate.swift
  LuckyCardGame/LuckyCardGame/App/Base.lproj/LaunchScreen.storyboard
  LuckyCardGame/LuckyCardGame/App/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/Assets.xcassets/CardBackSideImage.imageset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets.xcassets/CardBackSideImage.imageset/Image.png
  LuckyCardGame/LuckyCardGame/Extension/CGRect+UIEdgeInsets.swift
  LuckyCardGame/LuckyCardGame/Extension/CGSize+UIEdgeInsets.swift
  LuckyCardGame/LuckyCardGame/Extension/String+UIImage.swift
  LuckyCardGame/LuckyCardGame/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardDeck.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardGame.swift
  LuckyCardGame/LuckyCardGame/Model/Protocol/CardDeckProtocol.swift
  LuckyCardGame/LuckyCardGame/Model/Protocol/CardProtocol.swift
  LuckyCardGame/LuckyCardGame/View/CardDeckStackView.swift
  LuckyCardGame/LuckyCardGame/View/CardDeckView.swift
  LuckyCardGame/LuckyCardGame/View/CardView.swift
  LuckyCardGame/LuckyCardGame/View/DealerCardDeckView.swift
  LuckyCardGame/LuckyCardGame/View/GameBoardView.swift
  LuckyCardGame/LuckyCardGame/View/GameView.swift
  LuckyCardGame/LuckyCardGame/View/LayoutConstant.swift
  LuckyCardGame/LuckyCardGame/View/LuckyCardGameBaseView.swift
  README.md
Labels: step1-3

#62 [정도현] 카드 나눠주기 코드 구현
  LuckyCardGame/LuckyCardGame/Application/SceneDelegate.swift
  LuckyCardGame/LuckyCardGame/Assets/Assets.xcassets/lucky_card_back.imageset/Contents.json
  LuckyCardGame/LuckyCardGame/Assets/Assets.xcassets/lucky_card_back.imageset/lucky_card_back.png
  LuckyCardGame/LuckyCardGame/Model/Card/CardEmojiType.swift
  LuckyCardGame/LuckyCardGame/Model/Card/CardValue.swift
  LuckyCardGame/LuckyCardGame/Model/Card/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/Card/LuckyCardMaker.swift
  LuckyCardGame/LuckyCardGame/Model/Card/RandomBuildable.swift
  LuckyCardGame/LuckyCardGame/Model/Card/Validator/CardValueValidator.swift
  LuckyCardGame/LuckyCardGame/Model/Deck/Deck.swift
  LuckyCardGame/LuckyCardGame/Model/Deck/LuckyCardDeck.swift
  LuckyCardGame/LuckyCardGame/Model/Field/LuckyGameField.swift
  LuckyCardGame/LuckyCardGame/Model/Game/LuckyCardGame.swift
  LuckyCardGame/LuckyCardGame/Model/GameStrategy/FivePeopleGameStrategy.swift
  LuckyCardGame/LuckyCardGame/Model/GameStrategy/FourPeopleGameStrategy.swift
  LuckyCardGame/LuckyCardGame/Model/GameStrategy/GameStrategy.swift
  LuckyCardGame/LuckyCardGame/Model/GameStrategy/ThreePeopleGameStrategy.swift
  LuckyCardGame/LuckyCardGame/Model/LuckyCardMaker.swift
  LuckyCardGame/LuckyCardGame/Model/Player/CardGamePlayable.swift
  LuckyCardGame/LuckyCardGame/Model/Player/CardReceivable.swift
  LuckyCardGame/LuckyCardGame/Model/Player/CardgameDealable.swift
  LuckyCardGame/LuckyCardGame/Model/Player/LuckyCardDealer.swift
  LuckyCardGame/LuckyCardGame/Model/Player/LuckyCardGamePlayer.swift
  LuckyCardGame/LuckyCardGame/Model/Player/PlayerDataBase.swift
  LuckyCardGame/LuckyCardGame/View/CardAddable.swift
  LuckyCardGame/LuckyCardGame/View/CardRemovable.swift
  LuckyCardGame/LuckyCardGame/View/CardView.swift
  LuckyCardGame/LuckyCardGame/View/GameBoardViewCalculator.swift
  LuckyCardGame/LuckyCardGame/View/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/View/PlayerboardView.swift
  LuckyCardGame/LuckyCardGame/View/RoundBoardView.swift
  LuckyCardGame/LuckyCardGame/View/RoundCardBoardView.swift
  LuckyCardGame/LuckyCardGame/View/RoundView.swift
  LuckyCardGame/LuckyCardGame/ViewModel/GameBoardViewModel.swift
Labels: step1-3

#64 [변상연] 게임로직 테스트코드 작성, 게임로직 구현
  .gitignore
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/byeonsang-yeon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/sangyeon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/Source/Class/LuckyCardGame.swift
  LuckyCardGame/LuckyCardGame/Source/Class/LuckyCardManager.swift
  LuckyCardGame/LuckyCardGame/Source/Class/LuckyGame.swift
  LuckyCardGame/LuckyCardGame/Source/Class/Protocol/LuckyCardManagerProtocol.swift
  LuckyCardGame/LuckyCardGame/Source/Model/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Source/Model/Player.swift
  LuckyCardGame/LuckyCardGame/Source/Model/SelectedCard.swift
  LuckyCardGame/LuckyCardGame/Source/View/GameBoardView.swift
  LuckyCardGame/LuckyCardGame/Source/View/LuckyCardView.swift
  LuckyCardGame/LuckyCardGame/Source/View/LuckyGameView.swift
  LuckyCardGame/LuckyCardGame/Source/View/PersonalCardBoardView.swift
  LuckyCardGame/LuckyCardGame/Source/View/RoundView.swift
  LuckyCardGame/LuckyCardGame/Source/ViewController/CardBoardViewController.swift
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
  LuckyCardGame/LuckyCardGameTests/Mock/MockLuckyCardManager.swift
  README.md
Labels: step1-4, step2-1

#65 [고정민] - (1-4), (2-1) 게임로직 구현하기 및 리팩토링
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/kojeongmin.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcshareddata/xcschemes/LuckyCardGame.xcscheme
  LuckyCardGame/LuckyCardGame.xcodeproj/xcshareddata/xcschemes/LuckyCardGameTests.xcscheme
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/kojeongmin.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame.xctestplan
  LuckyCardGame/LuckyCardGame/Common/UIColors+Extension.swift
  LuckyCardGame/LuckyCardGame/Component/BottomContainerView.swift
  LuckyCardGame/LuckyCardGame/Component/CardContainerView.swift
  LuckyCardGame/LuckyCardGame/Component/CardView.swift
  LuckyCardGame/LuckyCardGame/Component/GameView.swift
  LuckyCardGame/LuckyCardGame/Entity/GameManager.swift
  LuckyCardGame/LuckyCardGame/Entity/SafeAreaFrame.swift
  LuckyCardGame/LuckyCardGame/GameBoardViewController.swift
  LuckyCardGame/LuckyCardGame/Service/LuckyGame.swift
  LuckyCardGame/LuckyCardGameManagerTests/LuckyCardGameManagerTests.swift
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameServiceTests.swift
  LuckyCardGame/LuckyGameTests/LuckyGameTests.swift
  README.md
Labels: step1-4, step2-1

#66 [배남석] 게임로직 구현하기
  .DS_Store
  LuckyCardGame/BoardTests/BoardTests.swift
  LuckyCardGame/DividerTests/DividerTests.swift
  LuckyCardGame/EnumTests/EnumTests.swift
  LuckyCardGame/LuckyCardFactoryTests/LuckyCardFactoryTests.swift
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/project.xcworkspace/xcuserdata/baenamseok.xcuserdatad/UserInterfaceState.xcuserstate
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/baenamseok.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  LuckyCardGame/LuckyCardGame/Model/Class/Card.swift
  LuckyCardGame/LuckyCardGame/Model/Class/CardFactory.swift
  LuckyCardGame/LuckyCardGame/Model/Class/DefaultLuckyGameManager.swift
  LuckyCardGame/LuckyCardGame/Model/Class/Divider.swift
  LuckyCardGame/LuckyCardGame/Model/Class/LuckyCard.swift
  LuckyCardGame/LuckyCardGame/Model/Class/LuckyCardFactory.swift
  LuckyCardGame/LuckyCardGame/Model/Class/LuckyGame.swift
  LuckyCardGame/LuckyCardGame/Model/Class/Player.swift
  LuckyCardGame/LuckyCardGame/Model/Class/Validator.swift
  LuckyCardGame/LuckyCardGame/Model/Struct/Board.swift
  LuckyCardGame/LuckyCardGame/Util/Enum/BoardType.swift
  LuckyCardGame/LuckyCardGame/Util/Enum/FlippedCardType.swift
  LuckyCardGame/LuckyCardGame/Util/Mock/MockDivider.swift
  LuckyCardGame/LuckyCardGame/Util/Mock/MockGround.swift
  LuckyCardGame/LuckyCardGame/Util/Mock/MockValidator.swift
  LuckyCardGame/LuckyCardGame/View/CardView.swift
  LuckyCardGame/LuckyCardGame/ViewController/ViewController.swift
  LuckyCardGame/LuckyCardGame/etc/Assets.xcassets/CardBackImage.imageset/CardBackImage.png
  LuckyCardGame/LuckyCardGame/etc/Assets.xcassets/CardBackImage.imageset/Contents.json
  LuckyCardGame/LuckyCardGameTests/LuckyCardGameTests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITests.swift
  LuckyCardGame/LuckyCardGameUITests/LuckyCardGameUITestsLaunchTests.swift
  LuckyCardGame/LuckyCardTests/LuckyCardTests.swift
  LuckyCardGame/LuckyGameTests/LuckyGameTests.swift
  LuckyCardGame/PlayerTests/PlayerTests.swift
  LuckyCardGame/ValidatorTests/ValidatorTests.swift
  README.md
Labels: step1-4, step2-1

#67 [양승현] (1-4) 게임 로직 구현하기. (2-1) 게임 로직 구현하기(이어서), (2-2) 게임규칙 추가하기 일부 UI구현했습니다.
  LuckyCardGame/LuckyCardGame.xcodeproj/project.pbxproj
  LuckyCardGame/LuckyCardGame.xcodeproj/xcshareddata/xcschemes/LuckyCardGame.xcscheme
  LuckyCardGame/LuckyCardGame.xcodeproj/xcuserdata/yangseunghyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  LuckyCardGame/LuckyCardGame.xctestplan
  LuckyCardGame/LuckyCardGameTests/LuckyGame/Manager/LuckyCardGameManagerTests.swift
  LuckyCardGame/LuckyCardGameTests/LuckyGame/SystemUnderTests/Manager/LuckyGameTests.swift
  LuckyCardGame/LuckyCardGameTests/LuckyGame/SystemUnderTests/Model/LuckyCardDeckImplTests.swift
  LuckyCardGame/LuckyCardGameTests/LuckyGame/SystemUnderTests/Model/SelectedLuckyCardDeckImplTests.swift
  LuckyCardGame/LuckyCardGameTests/LuckyGame/TestDouble/Stub/StubLuckyGame.swift
  LuckyCardGame/LuckyCardGameTests/LuckyGame/TestDouble/Tests/StubLuckyGameTests.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Manager/LuckyGame.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Card/LuckyCardShapeType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Deck/LuckyCardDeckImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Deck/SelectedLucykCardDeckImpl.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Player/Player.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Model/Player/PlayerBoardType.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Card/CardGameManager.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Deck/Deck.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/Deck/SelectedLuckyCardDeckProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/ViewModel/PlayerCardBoardViewModelProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/Protocol/ViewModel/PlayersCardBoardAreaViewModelProtocol.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Common/CardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Content/LuckyCardGameContentView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Content/PlayerCardBoardView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/CardAreaView/Footer/LuckyCardGameFooter.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/LuckyCardGameView/LuckyCardGameHeader.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/View/LuckyCardGameView/LuckyCardGameView.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewController/PlayersCardAreaViewController.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/LuckyCardGameFooterViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/LuckyCardViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/PlayerCardBoardViewModel.swift
  LuckyCardGame/Source/Feature/LuckyCardGame/ViewModel/PlayersCardBoardAreaViewModel.swift
  README.md
Labels: step1-4, step2-1
